name: Build/Push Telemetria API & Deploy

on:
  push:
    branches: ["master"] # cambia a "main" si aplica
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build_push_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/proyectosicm/telemetria-peru-api:latest
            ghcr.io/proyectosicm/telemetria-peru-api:${{ github.sha }}

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /var/www/telemetria-peru
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml up -d --remove-orphans --force-recreate
            docker image prune -f
